# To make use of pre-commit-config file, install pre-commit using pip
# `pip install pre-commit`
# Run `pre-commit install` to install pre-commit git hook script
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
      - id: cargo-check