FROM ubuntu:latest

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl wget build-essential postgresql-client libssl-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
        chmod +x /usr/bin/yq


# Install Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH=/root/.cargo/bin:$PATH

WORKDIR /app

COPY . .

ENV RUSTFLAGS='-C target-feature=+crt-static'

# Build the project in debug mode and place the binary in /app
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build --target x86_64-unknown-linux-gnu && \
    cp ./target/x86_64-unknown-linux-gnu/debug/mb-ia /app/mb-ia

ENV RUN_MODE=development

# Set the working directory to /app and run the binary
CMD ["/app/mb-ia"]
