FROM rust:latest AS builder

WORKDIR /app

COPY . .

ENV RUSTFLAGS='-C target-feature=+crt-static'
ENV SQLX_OFFLINE=true

RUN cargo build --release --target x86_64-unknown-linux-gnu && \
    cp ./target/x86_64-unknown-linux-gnu/release/mb-ia /mb-ia
FROM scratch

WORKDIR /app
COPY --from=builder /mb-ia ./app

COPY --from=builder /app/config /app/config
CMD ["/app/app"]

