FROM metabrainz/base-image:latest

RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends -y \
        rustc cargo build-essential unzip curl wget iputils-ping pkg-config libssl-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


ENV RUN_MODE=production

WORKDIR /app

COPY . .

RUN cargo build --release --target x86_64-unknown-linux-gnu && \
    cp ./target/x86_64-unknown-linux-gnu/release/mb-ia /app/mb-ia

CMD ["/app/mb-ia"]