[logs]
debug = true
error = true
warning = true
info = true

[poller_task]
poll_interval = 10

# Takes pending urls and send a request to IA to archive them
[archival_task]
# The minimum interval of time in seconds before another url start getting archived
job_interval = 15
# The amount of concurent archival requests to create
worker_count = 1
# The amount of times an url can be retried
max_retry = 3
# Remove the row if it has been more than X elapsed seconds since its creation
allow_remove_row_after = 86400
# How long to wait between url retries
retry_interval = 86400 # 60*60*24 seconds

# Watch over the pending archivals
[status_watch_task]
# The minimum interval of time in seconds before another archival start getting watched
job_interval = 15
# The amount of concurent watchers to create. A watcher will follow ONLY one archival request until it ends.
worker_count = 50
# The amount of times the task can try fetching the url
max_retry = 3
# How long to wait between url retries
retry_interval = 86400 # 60*60*24 seconds

# Cleanup the database
[cleaner_task]
# The number of minutes between runs
job_interval = 5

[wayback_machine_api]
save_endpoint_url = "http://web.archive.org/save"
status_endpoint_url =  "http://web.archive.org/save/status"

# How many save requests to allow per minute across all workers
save_rate_limit = 1

# How many status requests to allow per minute across all workers
status_rate_limit = 4