debug = true

[wayback_machine_api]
myaccesskey = "OqvSkX8Sv5hblwrv"
mysecret =  "tjow7aOFJAWokDsX"

[retry_task]
retry_interval = 120 # 2 min
allow_remove_row_after = 300 # 5 min

[sentry]
url = "enter your project url"